### ISSUE TITLE
5.客户端轮询好像没实现?

### ISSUE THREAD

**Issue by punkmonday** [b2stry/seckill#2]
客户端轮询是使用什么机制?

**Comment by b2stry** [comment]
在resources/static/goods_detail.htm里面，代码如下：

 function getMiaoshaResult(goodsId) {
        g_showLoading();
        $.ajax({
            url: "/seckill/result",
            type: "GET",
            data: {
                goodsId: goodsId,
            },
            success: function (data) {
                if (data.code == 0) {
                    var result = data.data;
                    if (result < 0) {
                        layer.msg("对不起，秒杀失败");
                    } else if (result == 0) {//继续轮询
                        setTimeout(function () {
                            getMiaoshaResult(goodsId);
                        }, 50);
                    } else {
                        layer.confirm("恭喜你，秒杀成功！查看订单？", {btn: ["确定", "取消"]},
                            function () {
                                window.location.href = "/order_detail.htm?orderId=" + result;
                            },
                            function () {
                                layer.closeAll();
                            });
                    }
                } else {
                    layer.msg(data.msg);
                }
            },
            error: function () {
                layer.msg("客户端请求有误");
            }
        });
    }

**Comment by punkmonday** [comment]
非常感谢
